Change TBB header path

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4387,13 +4387,13 @@ then :
 printf "%s\n" "#define STDC_HEADERS 1" >>confdefs.h
 
 fi
-ac_fn_cxx_check_header_compile "$LINENO" "oneapi/tbb.h" "ac_cv_header_oneapi_tbb_h" "$ac_includes_default"
-if test "x$ac_cv_header_oneapi_tbb_h" = xyes
+ac_fn_cxx_check_header_compile "$LINENO" "tbb/tbb.h" "ac_cv_header_tbb_tbb_h" "$ac_includes_default"
+if test "x$ac_cv_header_tbb_tbb_h" = xyes
 then :
   TBBFLAG=-DTBB;TBBLIBS=-ltbb
 else $as_nop
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: parallel computing is disabled becuase oneapi/tbb.h (Intel TBB) is not found" >&5
-printf "%s\n" "$as_me: WARNING: parallel computing is disabled becuase oneapi/tbb.h (Intel TBB) is not found" >&2;}
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: parallel computing is disabled becuase tbb/tbb.h (Intel TBB) is not found" >&5
+printf "%s\n" "$as_me: WARNING: parallel computing is disabled becuase tbb/tbb.h (Intel TBB) is not found" >&2;}
 fi
 
 
